name: deploy
on: release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/download-artifact@v3
        with:
          name: Artifacts
          path: distfiles

      - name: copy file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: distfiles/*,server-scripts/*
          target: /tmp/minecraft